name = "quran-api"
main = "src/index.ts"
compatibility_date = "2024-02-01"

[[d1_databases]]
binding = "DB"
database_name = "quran-db"
database_id = "ignored-locally"
migrations_dir = "database/migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "bd982fc45d924e81b222f897a273cd8e"
preview_id = "95899259b28b43cdac7ad45a693e964a"


[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "quran-assets"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "dev-secret-change-in-production"
ASSETS_BASE_URL = "https://assets.quran.in.th"
